Proyecto/Apps/productos/urls.py
from django.urls import path
from . import views

app_name = 'productos'

urlpatterns = [
    path('explorar/', views.explorar_productos, name='explorar'),
    path('lista/', views.lista_productos, name='lista_productos'),
    path('agregar/', views.agregar_producto, name='agregar_producto'),
    path('actualizar/<int:pk>/', views.actualizar_producto, name='actualizar_producto'),
    path('eliminar/<int:pk>/', views.eliminar_producto, name='eliminar_producto'),
    path('producto/<int:pk>/', views.detalle_producto, name='detalle_producto'),
]

Proyecto/Apps/usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'usuarios'

urlpatterns = [
    path('registro/', views.registro, name='registro'),
    path('perfil/', views.actualizar_perfil, name='perfil'),
    path('login/', views.login_view, name='login'),
    path('perfil/<int:pk>/', views.perfil_usuario, name='perfil'),
    path('', views.home, name='home'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('editar_perfil/', views.editar_perfil, name='editar_perfil'),
]

Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from Proyecto.views import bienvenida
from Apps.usuarios import views as usuario_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', usuario_views.home, name='home'),  # Página de inicio
    path('bienvenida/', bienvenida),
    path('usuarios/', include('Apps.usuarios.urls')),
    path('productos/', include('Apps.productos.urls')),
    path('resenas/', include('Apps.resenas.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Proyecto/Apps/productos/models.py
from django.db import models
from django.contrib.auth.models import User

class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to='productos/', null=True, blank=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

# Create your models here.

Proyecto/Apps/productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['nombre', 'descripcion', 'precio', 'imagen']
        

Proyecto/Apps/productos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Producto
from .forms import ProductoForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def explorar_productos(request):
    return render(request, 'productos/explorar.html')

def lista_productos(request):
    productos = Producto.objects.all()
    return render(request, 'productos/lista_productos.html', {'productos': productos})

@login_required
def agregar_producto(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES)
        if form.is_valid():
            producto = form.save(commit=False)
            producto.usuario = request.user  # Asigna el usuario actual
            producto.save()
            return redirect('productos:lista_productos')
    else:
        form = ProductoForm()
    return render(request, 'productos/agregar_producto.html', {'form': form})

@login_required
def actualizar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if producto.usuario != request.user:
        return redirect('productos:lista_productos')  # Redirigir si el usuario no es el propietario

    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES, instance=producto)
        if form.is_valid():
            form.save()
            return redirect('productos:lista_productos')
    else:
        form = ProductoForm(instance=producto)
    return render(request, 'productos/actualizar_producto.html', {'form': form})

@login_required
def eliminar_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    if producto.usuario != request.user:
        return redirect('productos:lista_productos')  # Redirigir si el usuario no es el propietario

    if request.method == 'POST':
        producto.delete()
        return redirect('productos:lista_productos')
    return render(request, 'productos/eliminar_producto.html', {'producto': producto})

def detalle_producto(request, pk):
    producto = get_object_or_404(Producto, pk=pk)
    return render(request, 'productos/detalle_producto.html', {'producto': producto})

Proyecto/Apps/templates/productos/actualizar_producto.html
{% extends 'base.html' %}

{% block content %}
    <h1>Actualizar Producto</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Guardar cambios</button>
    </form>
    <a href="{% url 'productos:lista_productos' %}">Volver</a>
{% endblock %}

Proyecto/Apps/templates/productos/agregar_producto.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <h1 class="mb-4">Agregar Producto</h1>
        <form method="post" enctype="multipart/form-data">  <!-- Asegúrate de incluir enctype -->
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success">Guardar</button>
        </form>
    </div>
{% endblock %}

Proyecto/Apps/templates/productos/detalle_producto.html
{% extends 'base.html' %}
{% load resenas_extras %}

{% block content %}
    <div class="container mt-4">
        <h1 class="mb-4">{{ producto.nombre }}</h1>
        <div class="card">
            <div class="card-body">
                <p class="card-text">{{ producto.descripcion }}</p>
                <p class="card-text"><strong>Precio:</strong> {{ producto.precio }}</p>
                {% if producto.imagen %}
                <img src="{{ producto.imagen.url }}" class="img-fluid" alt="{{ producto.nombre }}" style="width: 300px; height: 300px; object-fit: cover;">
                {% endif %}
                <p class="card-text mt-3"><strong>Publicado por:</strong> <a href="{% url 'usuarios:perfil' producto.usuario.pk %}">{{ producto.usuario.username }}</a></p> <!-- Enlace al perfil del usuario -->
                <p class="card-text mt-3"><strong>Calificación:</strong>
                    {% with producto.usuario.resenas_recibidas.all as resenas %}
                        {% if resenas %}
                            {{ resenas|promedio_calificaciones }} / 5
                        {% else %}
                            Sin calificaciones
                        {% endif %}
                    {% endwith %}
                </p>
                {% if user.is_authenticated %}
                    <p class="card-text mt-3"><strong>Teléfono:</strong> {{ producto.usuario.perfil.telefono }}</p>
                    <p class="card-text mt-3"><strong>Email de contacto:</strong> {{ producto.usuario.perfil.email_contacto }}</p>
                {% else %}
                    <p class="card-text mt-3"><strong>Contactar al vendedor:</strong> <a href="{% url 'usuarios:login' %}">Inicia sesión para ver los métodos de contacto</a></p>
                {% endif %}
                <a href="{% url 'productos:lista_productos' %}" class="btn btn-primary mt-3">Volver a la lista</a>
            </div>
        </div>
    </div>
{% endblock %}

Proyecto/Apps/templates/productos/eliminar_producto.html
<!-- productos/templates/productos/eliminar_producto.html -->
{% extends 'base.html' %}

{% block content %}
    <h1>Eliminar Producto</h1>
    <p>¿Estás seguro de que quieres eliminar "{{ producto.nombre }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Eliminar</button>
    </form>
    <a href="{% url 'productos:lista_productos' %}">Cancelar</a>
{% endblock %}

Proyecto/Apps/templates/productos/explorar.html
<style>
    
</style>
{% extends 'base.html' %}

{% block title %}Explorar Productos{% endblock %}
<a href="{% url 'agregar_producto' producto.pk %}" class="btn btn-primary">Agregar Producto</a>


{% block content %}
    <h1>Explorar Productos</h1>
    <p>Aquí se mostrarán todos los productos disponibles.</p>

    <div class="row">
        {% if productos %}
            {% for producto in productos %}
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <img src="{{ producto.imagen.url }}" class="card-img-top" alt="{{ producto.nombre }}" style="max-height: 200px; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-title">{{ producto.nombre }}</h5>
                            <p class="card-text">{{ producto.descripcion|truncatewords:20 }}</p>
                            <p><strong>Precio:</strong> ${{ producto.precio }}</p>
                            <a href="{% url 'detalle_producto' producto.pk %}" class="btn btn-primary">Ver Detalles</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No hay productos disponibles en este momento.</p>
        {% endif %}
    </div>
{% endblock %}

Proyecto/Apps/templates/productos/lista_productos.html
{% extends 'base.html' %}
{% load static %}
{% load resenas_extras %}

{% block content %}
    <div class="container mt-4">
        <h1 class="mb-4">Lista de Productos</h1>

        <!-- Botón para agregar un nuevo producto -->
        {% if user.is_authenticated %}
            <a href="{% url 'productos:agregar_producto' %}" class="btn btn-success mb-3">Agregar Producto</a>
        {% endif %}

        <!-- Tabla para listar los productos -->
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Imagen</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Descripción</th>
                    <th scope="col">Precio</th>
                    <th scope="col">Calificación 1 al 5</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        {% if producto.imagen %}
                            <img src="{{ producto.imagen.url }}" class="img-thumbnail" alt="{{ producto.nombre }}" style="width: 100px; height: 100px;">
                        {% else %}
                            <img src="{% static 'images/default-product.jpg' %}" class="img-thumbnail" alt="Imagen no disponible" style="width: 100px; height: 100px;">
                        {% endif %}
                    </td>
                    <td><a href="{% url 'productos:detalle_producto' producto.pk %}">{{ producto.nombre }}</a></td> <!-- Enlace a detalles del producto -->
                    <td>{{ producto.descripcion|truncatewords:10 }}</td>
                    <td>{{ producto.precio }}</td>
                    <td>
                        {% with producto.usuario.resenas_recibidas.all as resenas %}
                            {% if resenas %}
                                {{ resenas|promedio_calificaciones }} / 5
                            {% else %}
                                Sin calificaciones
                            {% endif %}
                        {% endwith %}
                    </td>
                    <td>
                        {% if producto.usuario == user %}
                            <!-- Botón para editar el producto -->
                            <a href="{% url 'productos:actualizar_producto' producto.pk %}" class="btn btn-primary btn-sm">Editar</a>

                            <!-- Botón para eliminar el producto -->
                            <a href="{% url 'productos:eliminar_producto' producto.pk %}" class="btn btn-danger btn-sm">Eliminar</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}